export const Events = {
  LOGIN_MODAL_VISIBILITY_UPDATED: "LOGIN_MODAL_VISIBILITY_UPDATED",
  LOGIN_MODAL_REQUESTED: "LOGIN_MODAL_REQUESTED",

  USER_SUCCESSFULLY_AUTHENTICATED: "USER_SUCCESSFULLY_AUTHENTICATED"
};
