export const Events = {
  PRODUCT_PAGE_SELECTED: "PRODUCT_PAGE_SELECTED",
  HOME_PAGE_SELECTED: "HOME_PAGE_SELECTED",
  LOGIN_MODAL_REQUEST_SUBMITTED: "LOGIN_MODAL_REQUEST_SUBMITTED",
  LOGOUT_USER_REQUEST_SUBMITTED: "LOGOUT_USER_REQUEST_SUBMITTED",
  CHECKOUT_PAGE_REQUEST_SUBMITTED: "CHECKOUT_PAGE_REQUEST_SUBMITTED"
};
