export const Events = {
  PRODUCTS_LIST_LOADED: "ProductsListLoaded",
  PRODUCT_SELECTED_FOR_DETAILS: "ProductSelectedForDetails",
  ADD_TO_SHOPPING_CART_TRIGGERED: "ADD_TO_SHOPPING_CART_TRIGGERED"
};
